### ISSUE TITLE
process_batch might not be working

### ISSUE THREAD

**Issue by adieyal** [stysmmaker/stable-diffusion-webui-randomize#3]
The script worked well with `process` but doesn't seem to run with `process_batch`

**Comment by stysmmaker** [comment]
I think this might only be true for when it attempts to generate using highres. fix -- can you confirm that's the case? If not then the randomization parameters used might be helpful.

**Comment by adieyal** [comment]
I don't think it's being called at all. I updated to the latest version.

Prompt: I love red roses
Steps: 30,50,5

![Screenshot from 2022-11-12 17-34-12](https://user-images.githubusercontent.com/420786/201481670-b7775e3a-b07e-45bc-be50-4147dac6b340.png)
![Screenshot from 2022-11-12 17-34-24](https://user-images.githubusercontent.com/420786/201481668-a1d2cc6e-01ed-48ea-9fcd-616d03538ea2.png)
![Screenshot from 2022-11-12 17-34-45](https://user-images.githubusercontent.com/420786/201481665-b8e20c6e-ca55-4612-839f-941f37a6265c.png)

I also edited the file and added `import pdb; pdb.set_trace()` right after `def process_batch(...)`. The line never gets run.

**Comment by stysmmaker** [comment]
Can't reproduce it on my end, I get the debugger if I include that and the script runs fine. I'm on the latest commit of the webui (https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/98947d173e3f1667eba29c904f681047dea9de90) if that helps.

**Comment by adieyal** [comment]
Gotcha - for some reason my webui stopped auto updating.
